version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
    networks:
      - proxy

  flask:
    entrypoint: python3
    build: ./backend
    command: app.py
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/searchapp'
    ports:
      - '12344:12344'
    networks:
      - proxy

  celery:
    entrypoint: celery
    build: ./backend
    command: -A worker worker --loglevel=debug
    volumes:
      - '.:/searchapp'
    networks:
      - proxy
  
  traefik:
    image: traefik
    command: --docker
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/certs/:/certs/

  nginx:
    build: ./frontend
    volumes:
     - '.:/searchapp'
    networks:
     - proxy
    labels:
      - traefik.port=80
      - traefik.backend=nginx
      - traefik.frontend.passHostHeader=true
      - traefik.enable=true
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true

volumes:
  redis:
